// src/components/AccordionSection.tsx
import type { ReactNode } from "react";
import { Disclosure, DisclosureButton, DisclosurePanel } from "@headlessui/react";
import { FiChevronRight } from "react-icons/fi";
import { usePersistedSectionCollapse } from "@/hooks/usePersistedSectionCollapse";
import { cn } from "@/utils/cn";

type AccordionSectionProps = {
  title: string;
  defaultOpen?: boolean;
  children: ReactNode;
};

/** アコーディオン (開閉可能) コンポーネント */
export function AccordionSection({ title, defaultOpen = false, children }: AccordionSectionProps) {
  const { isOpen, toggleOpen } = usePersistedSectionCollapse(title, defaultOpen);
  return (
    <Disclosure defaultOpen={isOpen}>
      {({ open }) => (
        <section className="space-y-1">
          <h3 className="flex items-center justify-between gap-1">
            <DisclosureButton
              as="button"
              onClick={toggleOpen}
              aria-expanded={open}
              className="flex items-center rounded py-0.5 pr-1 text-left text-sm text-slate-800 outline-none hover:bg-slate-100 hover:text-black"
            >
              <FiChevronRight
                aria-hidden="true"
                className={cn("h-4 w-4 shrink-0", open ? "rotate-90" : "rotate-0")}
              />
              <span>{title}</span>
            </DisclosureButton>
          </h3>

          <DisclosurePanel className="mb-2 overflow-hidden border border-slate-400 bg-slate-50/80">
            {children}
          </DisclosurePanel>
        </section>
      )}
    </Disclosure>
  );
}

// src/components/AccordionSection.vue
<script setup lang="ts">
import { Disclosure, DisclosureButton, DisclosurePanel } from "@headlessui/vue";
import { FeChevronRight } from "@kalimahapps/vue-icons/fe";
import { usePersistedSectionCollapse } from "@/composables/usePersistedSectionCollapse";
import { cn } from "@/utils/cn";

const props = withDefaults(
  defineProps<{
    title: string;
    defaultOpen?: boolean;
  }>(),
  {
    defaultOpen: false,
  },
);

const { isOpen, toggleOpen } = usePersistedSectionCollapse(props.title, props.defaultOpen);
</script>

<template>
  <Disclosure :default-open="isOpen">
    <template #default="{ open }">
      <section class="space-y-1">
        <h3 class="flex items-center justify-between gap-1">
          <DisclosureButton
            as="button"
            :aria-expanded="open"
            class="flex items-center rounded py-0.5 pr-1 text-left text-sm text-slate-800 outline-none hover:bg-slate-100 hover:text-black"
            @click="toggleOpen"
          >
            <FeChevronRight
              aria-hidden="true"
              :class="cn('h-4 w-4 shrink-0', open ? 'rotate-90' : 'rotate-0')"
            />
            <span>{{ title }}</span>
          </DisclosureButton>
        </h3>

        <DisclosurePanel class="mb-2 overflow-hidden border border-slate-400 bg-slate-50/80">
          <slot />
        </DisclosurePanel>
      </section>
    </template>
  </Disclosure>
</template>
