// src/components/SelectableText.tsx
import React, { useRef } from "react";
import { cn } from "@/utils/cn";

interface Props {
  children: React.ReactNode;
  className?: string;
}

/** クリックでテキスト全選択可能なコンポーネント */
export const SelectableText: React.FC<Props> = ({ children, className }) => {
  const spanRef = useRef<HTMLSpanElement>(null);

  const handleSelect = () => {
    const selection = window.getSelection();
    const range = document.createRange();

    if (!spanRef.current || !selection) return;

    range.selectNodeContents(spanRef.current);
    selection.removeAllRanges();
    selection.addRange(range);
  };

  return (
    <span
      ref={spanRef}
      onClick={handleSelect}
      // select-all を指定しておくと、トリプルクリックなど標準の挙動も補強される
      className={cn("inline-block select-all", className)}
    >
      {children}
    </span>
  );
};

// src/components/SelectableText.vue
<script setup lang="ts">
import { ref } from "vue";
import { cn } from "@/utils/cn";

defineProps<{
  className?: string;
  style?: Record<string, string>;
}>();

const spanRef = ref<HTMLSpanElement | null>(null);

/** クリックでテキスト全選択 */
function handleSelect() {
  const selection = window.getSelection();
  const range = document.createRange();

  if (!spanRef.value || !selection) return;

  range.selectNodeContents(spanRef.value);
  selection.removeAllRanges();
  selection.addRange(range);
}
</script>

<template>
  <span
    ref="spanRef"
    :class="cn('inline-block select-all', className)"
    :style="style"
    @click="handleSelect"
  >
    <slot />
  </span>
</template>
